services:
  postgres:
    image: postgres:16-alpine
    container_name: queryhub-postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB : ${POSTGRES_DB}
      POSTGRES_USER : ${POSTGRES_USER}
      POSTGRES_PASSWORD : ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - queryhub_pgdata:/var/lib/postgresql/data

  app:
   build:  .
   container_name: queryhub-app
   depends_on:
     - postgres
   env_file:
     - .env
   environment:
     APP_PORT: ${APP_PORT}
     POSTGRES_HOST: postgres
     POSTGRES_PORT_INTERNAL: 5432
     POSTGRES_DB: ${POSTGRES_DB}
     POSTGRES_USER: ${POSTGRES_USER}
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
   ports:
    - "${APP_PORT}:8080"

volumes:
  queryhub_pgdata:
